// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP9ZX_-727vLlvptZB_P0155LinbpZWkw',
    appId: '1:279068416482:web:5c968a1f467224c72281bb',
    messagingSenderId: '279068416482',
    projectId: 'f-lab-lfsjjw',
    authDomain: 'f-lab-lfsjjw.firebaseapp.com',
    storageBucket: 'f-lab-lfsjjw.appspot.com',
    measurementId: 'G-0TF59XJC7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmjnzfvGPKm8QsBRhSM_TxQLM8iu5zB3g',
    appId: '1:279068416482:android:7f31e839e699ba8c2281bb',
    messagingSenderId: '279068416482',
    projectId: 'f-lab-lfsjjw',
    storageBucket: 'f-lab-lfsjjw.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8yuZmgLsvMl1gdM0U66YGR1eavwEKbqM',
    appId: '1:279068416482:ios:6c4f7c25e505f11f2281bb',
    messagingSenderId: '279068416482',
    projectId: 'f-lab-lfsjjw',
    storageBucket: 'f-lab-lfsjjw.appspot.com',
    androidClientId: '279068416482-08p2gq29rmgfbclsnfbp6i41l0k2amcr.apps.googleusercontent.com',
    iosClientId: '279068416482-u7eq410tuta6eefkc91tka1k2cce6cd1.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.flab',
  );
}
